### ISSUE TITLE
libPlugin.BaseInstancePlugin.sendRcon() fails when state is "init"

### ISSUE THREAD

**Issue by Danielv123** [clusterio/clusterio#429]
server_select gives me the following awful error during startup every now and then:

```
[winston] Attempt to write logs with no transports {"message":"Unexpected error while handling server_select:update_instances_event:
Error: Expected state running,stopping but state is init
    at FactorioServer._check (C:\\Users\\danielv\\Documents\\project_files\\factorioClusterio\\packages\\lib\\factorio\\server.js:586:10)
    at FactorioServer.sendRcon (C:\\Users\\danielv\\Documents\\project_files\\factorioClusterio\\packages\\lib\\factorio\\server.js:971:8)
    at Instance.sendRcon (C:\\Users\\danielv\\Documents\\project_files\\factorioClusterio\\packages\\slave\\slave.js:207:29)
    at InstancePlugin.sendRcon (C:\\Users\\danielv\\Documents\\project_files\\factorioClusterio\\node_modules\\@clusterio\\lib\\plugin.js:232:30)
    at InstancePlugin.sendPendingRcon (C:\\Users\\danielv\\Documents\\project_files\\factorioClusterio\\node_modules\\@hornwitser\\server_select\\instance.js:21:29)
    at InstancePlugin.serialRcon (C:\\Users\\danielv\\Documents\\project_files\\factorioClusterio\\node_modules\\@hornwitser\\server_select\\instance.js:35:9)
    at InstancePlugin.updateInstancesEventHandler 
(C:\\Users\\danielv\\Documents\\project_files\\factorioClusterio\\node_modules\\@hornwitser\\server_select\\instance.js:70:14)
    at Instance.<anonymous> (C:\\Users\\danielv\\Documents\\project_files\\factorioClusterio\\packages\\lib\\plugin.js:710:80)
    at C:\\Users\\danielv\\Documents\\project_files\\factorioClusterio\\node_modules\\@clusterio\\lib\\link\\messages.js:1054:13
    at Instance._processHandler (C:\\Users\\danielv\\Documents\\project_files\\factorioClusterio\\packages\\lib\\link\\link.js:125:4)","level":"error"}
```

Except its formatted like this for some reason:

![](https://i.imgur.com/8XSiT5N.png)

**Comment by Hornwitser** [comment]
Attempt to write logs with no transports happens when a plugin has its own copy of `@clusterio/lib` with its own uninitialized logger and then attempts to log to that.

You can see in your stack trace that you have both
Documents\project_files\factorioClusterio\packages\lib\link.js
Documents\project_files\factorioClusterio\node_modules\@clusterio\lib\link\messages.js
Which seems likely to be two separate installations of `@clusterio/lib`.

**Comment by Danielv123** [comment]
Yep, I guess thats because of https://github.com/Hornwitser/server_select/blob/clusterio-2.0/package.json#L25

Wouldn't the correct way to do this in plugins be to use * or something, and let lerna pick the dependency installed by master/slave?

**Comment by Danielv123** [comment]
Closing since its not a clusterio issue.
