### ISSUE TITLE
Clusterio Instance crashes when having a portable, fuel consuming energy source in armor.

### ISSUE THREAD

**Issue by ElGauchooooo** [clusterio/clusterio#442]
I can reproduce this issue on my clusterio cluster with krastorio2 mod enabled. 

Krastorio mod offers a "Portable nuclear reactor" that consumes fuel cells to produce energy. As soon as i put one of those in my armor (doesn't matter if loaded with fuel cells or not) and switch the server, the instance crashes:

```
2021-12-14 21:56:12 [LEAVE] ElGaucho left the game
 216.857 Error MainLoop.cpp:1283: Exception at tick 10657767: The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_pre_player_left_game (ID 107)
LuaBurner doesn't contain key curently_burning.
stack traceback:
	[C]: in function '__index'
	modules/clusterio/serialize.lua:76: in function 'serialize_equipment_grid'
	modules/clusterio/serialize.lua:157: in function 'serialize_item_stack'
	modules/clusterio/serialize.lua:244: in function 'serialize_inventory'
	modules/inventory_sync/serialize.lua:12: in function 'serialize_inventories'
	modules/inventory_sync/serialize.lua:55: in function 'serialize_character'
	modules/inventory_sync/serialize.lua:156: in function 'serialize_player'
	...ntly-playing/modules/inventory_sync/upload_inventory.lua:18: in function 'upload_inventory'
	...rently-playing/modules/inventory_sync/inventory_sync.lua:270: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
 216.857 Error ServerMultiplayerManager.cpp:91: MultiplayerManager failed: "The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_pre_player_left_game (ID 107)
LuaBurner doesn't contain key curently_burning.
stack traceback:
	[C]: in function '__index'
	modules/clusterio/serialize.lua:76: in function 'serialize_equipment_grid'
	modules/clusterio/serialize.lua:157: in function 'serialize_item_stack'
	modules/clusterio/serialize.lua:244: in function 'serialize_inventory'
	modules/inventory_sync/serialize.lua:12: in function 'serialize_inventories'
	modules/inventory_sync/serialize.lua:55: in function 'serialize_character'
	modules/inventory_sync/serialize.lua:156: in function 'serialize_player'
	...ntly-playing/modules/inventory_sync/upload_inventory.lua:18: in function 'upload_inventory'
	...rently-playing/modules/inventory_sync/inventory_sync.lua:270: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>"
 216.857 Info ServerMultiplayerManager.cpp:797: updateTick(10657767) changing state from(InGame) to(Failed)
 216.861 Quitting: multiplayer error.
 217.203 Info ServerMultiplayerManager.cpp:140: Quitting multiplayer connection.
 217.203 Info ServerMultiplayerManager.cpp:797: updateTick(4294967295) changing state from(Failed) to(Closed)
 217.207 Info HttpSharedState.cpp:54: Downloading https://multiplayer.factorio.com/remove-game/11347851
 217.504 Info UDPSocket.cpp:218: Closing socket
 217.504 Info UDPSocket.cpp:248: Socket closed
 217.504 Info UDPSocket.cpp:218: Closing socket
 217.644 Info UDPSocket.cpp:218: Closing socket
 217.644 Info UDPSocket.cpp:248: Socket closed
 217.646 Goodbye
[error] Error in instance KickstartInstance:
Error: Factorio server unexpectedly shut down with code 1
    at ChildProcess._server.on (/tmp/clusterio/node_modules/@clusterio/lib/factorio/server.js:786:26)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

**Comment by ElGauchooooo** [comment]
Found the issue, there's a typo in Line 76 of /modules/clusterio/serialize.loa

`if burner.curently_burning then`

but should be:

`if burner.currently_burning then`

**Comment by Danielv123** [comment]
Haha, thats why we need testing with mods as well 👍

**Comment by ElGauchooooo** [comment]
Feel free to do it, havn't set up my environment right now.

**Comment by ElGauchooooo** [comment]
@Danielv123 Line 78 is the same spelling mistake. :)
