### ISSUE TITLE
Error Exporting data for settings

### ISSUE THREAD

**Issue by n0t49a1n** [clusterio/clusterio#566]
while export data on a previously running instance i get this 
Host Log file (host-2024-01-21.log)

```
{"instance_id":1413774143,"instance_name":"Solar4","level":"error","message":"Solar4:\nError: Connection closed\n    at EventEmitter.onEnd (/data/clusterio/node_modules/rcon-client/lib/rcon.js:113:45)\n    at EventEmitter.emit (node:events:531:35)\n    at Socket.<anonymous> (/data/clusterio/node_modules/rcon-client/lib/rcon.js:58:26)\n    at Socket.emit (node:events:519:28)\n    at TCP.<anonymous> (node:net:337:12)","timestamp":"2024-01-21T09:52:42.117Z"}
{"instance_id":1413774143,"instance_name":"Solar4","level":"warn","message":"__core__/graphics/icons/unknown.png not found","timestamp":"2024-01-21T09:52:42.125Z"}
{"instance_id":1413774143,"instance_name":"Solar4","level":"warn","message":"__core__/graphics/empty.png not found","timestamp":"2024-01-21T09:52:42.402Z"}
{"level":"error","message":"Unexpected error responding to InstanceExportDataRequest:\nError: Upload failed: 401 Unauthorized: Unauthorized\n    at Instance.handleInstanceExportDataRequest (/data/clusterio/node_modules/@clusterio/host/dist/src/Instance.js:911:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-01-21T09:52:47.768Z"}
```

Web Instance log
```
[error] Solar4:
Error: Connection closed
    at EventEmitter.onEnd (/data/clusterio/node_modules/rcon-client/lib/rcon.js:113:45)
    at EventEmitter.emit (node:events:531:35)
    at Socket.<anonymous> (/data/clusterio/node_modules/rcon-client/lib/rcon.js:58:26)
    at Socket.emit (node:events:519:28)
    at TCP.<anonymous> (node:net:337:12)
[warn] __core__/graphics/icons/unknown.png not found
[warn] __core__/graphics/empty.png not found
```

Web Host console log
```
[error] Unexpected error responding to InstanceExportDataRequest:
Error: Upload failed: 401 Unauthorized: Unauthorized
    at Instance.handleInstanceExportDataRequest (/data/clusterio/node_modules/@clusterio/host/dist/src/Instance.js:911:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by n0t49a1n** [comment]
Host console
```
[error] Unexpected error responding to InstanceExportDataRequest:
Error: Upload failed: 401 Unauthorized: Unauthorized
    at Instance.handleInstanceExportDataRequest (/data/clusterio/node_modules/@clusterio/host/dist/src/Instance.js:911:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Hornwitser** [comment]
See the [known issues](https://github.com/clusterio/clusterio?tab=readme-ov-file#known-issues) for it.:

>  - After migrating from Alpha 13 to Alpha 14 running an instance data export fails with the error `Upload failed: 401 Unauthorized` due to the host token being issued to a slave. To workaround this find the id of the host in the host config and generate a new host token with the same id. Stop the host and replace the value of the `host.controller_token` field in `config-host.json` with the new host token before starting it up again.

**Comment by n0t49a1n** [comment]
100% works sorry
