### ISSUE TITLE
Error during host-only installation on Raspberry Pi

### ISSUE THREAD

**Issue by RitnDev** [clusterio/clusterio#644]
Hello,

I encountered an error while installing Clusterio in host-only mode on my Raspberry Pi. Below are the details of the error:

```less
? (Linux only) Automatically download latest factorio release? Yes
? Plugins to install Player Auth, Statistics Exporter
info Downloading latest Factorio server release. This may take a while.
info Please wait, installing host
info Setting up plugins
info Setting up host
fatal
+------------------------------------------------------------+
| Unexpected error occured installing clusterio, please      |
| report it to https://github.com/clusterio/clusterio/issues |
+------------------------------------------------------------+
Error: Command failed: node_modules/.bin/clusteriohost config set host.id 750720563
/home/pi/clusterio/node_modules/@clusterio/lib/dist/node/src/lua_tools.js:27
    r ??= NaN;
      ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/pi/clusterio/node_modules/@clusterio/lib/dist/node/src/data/ModPack.js:33:34)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Socket.<anonymous> (internal/child_process.js:446:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12)

```

It appears to be a syntax error related to the ??= operator in the lua_tools.js file.

Could you please help me resolve this issue?

Thank you!

**Comment by Danielv123** [comment]
Hi, the version of node you are using is too old. See the readme for supported versionsOn 25 Jun 2024 21:19, Ritn ***@***.***> wrote:
Hello,
I encountered an error while installing Clusterio in host-only mode on my Raspberry Pi. Below are the details of the error:
? (Linux only) Automatically download latest factorio release? Yes
? Plugins to install Player Auth, Statistics Exporter
info Downloading latest Factorio server release. This may take a while.
info Please wait, installing host
info Setting up plugins
info Setting up host
fatal
+------------------------------------------------------------+
| Unexpected error occured installing clusterio, please      |
| report it to https://github.com/clusterio/clusterio/issues |
+------------------------------------------------------------+
Error: Command failed: node_modules/.bin/clusteriohost config set host.id 750720563
***@***.***/lib/dist/node/src/lua_tools.js:27
    r ??= NaN;
      ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> ***@***.***/lib/dist/node/src/data/ModPack.js:33:34)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Socket.<anonymous> (internal/child_process.js:446:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12)

It appears to be a syntax error related to the ??= operator in the lua_tools.js file.
Could you please help me resolve this issue?
Thank you!
### Tasks
