### ISSUE TITLE
Error starting instance

### ISSUE THREAD

**Issue by b4xster** [clusterio/clusterio#669]
I try start server from www and get error

Error starting instance
Unable to run server: Permission denied

clusterio work with space age ?

**Comment by b4xster** [comment]
[error] Unexpected error responding to InstanceStartRequest:
Error: Unable to run server: Permission denied
    at FactorioServer.create (/home/factorio/clusterio/node_modules/@clusterio/host/src/server.ts:883:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Instance.prepareSave (/home/factorio/clusterio/node_modules/@clusterio/host/src/Instance.ts:763:4)
    at async Instance.handleInstanceStartRequest (/home/factorio/clusterio/node_modules/@clusterio/host/src/Instance.ts:1006:15)
