### ISSUE TITLE
Error starting instance

### ISSUE THREAD

**Issue by b4xster** [clusterio/clusterio#670]
I try start server from www and get error

Error starting instance
Unable to run server: Permission denied

clusterio work with space age ?
```
[error] Unexpected error responding to InstanceStartRequest:
Error: Unable to run server: Permission denied
    at FactorioServer.create (/home/factorio/clusterio/node_modules/@clusterio/host/src/server.ts:883:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Instance.prepareSave (/home/factorio/clusterio/node_modules/@clusterio/host/src/Instance.ts:763:4)
    at async Instance.handleInstanceStartRequest (/home/factorio/clusterio/node_modules/@clusterio/host/src/Instance.ts:1006:15)
```

**Comment by Cooldude2606** [comment]
Which user are you running Clusterio as and who is the owner of the downloaded binary? This seams like a case where you have forgot to chown.

**Comment by b4xster** [comment]
Do you mean it ?

factorio@b4xnuc:~$ ls -l
total 4
drwxrwxrwx 10 factorio factorio 4096 Oct 27 19:12 clusterio
factorio@b4xnuc:~$

**Comment by Cooldude2606** [comment]
With `clusterio` as your working directory, run the following command to list the owner of all binaries.
`find -maxdepth 5 -type f -name factorio -ls`

Example output:
```
9313570 302320 -rwxr-xr-x   1 factorio factorio 309567716 Oct 22 16:04 ./factorio/2.0.9/bin/x64/factorio
9181064 203912 -rwxr-xr-x   1 factorio factorio 208800700 Aug 16 15:30 ./factorio/1.1.110/bin/x64/factorio
3413050 303508 -rwxr-xr-x   1 factorio factorio 310786196 Oct 25 12:43 ./factorio/2.0.11/bin/x64/factorio
3408163 303332 -rwxr-xr-x   1 factorio factorio 310605348 Oct 23 17:28 ./factorio/2.0.10/bin/x64/factorio
9175487 301980 -rwxr-xr-x   1 factorio factorio 309220380 Oct 21 14:27 ./factorio/2.0.8/bin/x64/factorio
```

**Comment by b4xster** [comment]
is different from yours

`factorio@b4xnuc:~/clusterio$  find -maxdepth 5 -type f -name factorio -ls
  1065278 303508 -rw-rw-r--   1 factorio factorio 310786196 paź 27 18:28 ./factorio/2.0.11/bin/x64/factorio
factorio@b4xnuc:~/clusterio$
`

**Comment by Cooldude2606** [comment]
Your binary is missing the execute permission. Run `chmod +x ./factorio/2.0.11/bin/x64/factorio`

Also you can use \``` text here \``` to create code blocks similar to my message.

**Comment by b4xster** [comment]
so thanks a lot, solving the problem generates another error from the server, not from clusterio (I downloaded 2.0.11 manually, maybe that's why there were no permissions)

``` [verbose] Writing server-settings.json
[verbose] Writing server-adminlist.json
[verbose] Writing server-banlist.json
[verbose] Writing server-whitelist.json
[info] Syncing mods
[info] Creating new save
   0.000 2024-10-27 22:14:02; Factorio 2.0.11 (build 79682, linux64, headless, space-age)
   0.011 Operating system: Linux (Ubuntu 24.10)
   0.011 Program arguments: "factorio/2.0.11/bin/x64/factorio" "--config" "instances/World/config.ini" "--create" "instances/World/saves/world.zip" 
   0.011 Config path: config.ini
   0.011 Read data path: /home/factorio/clusterio/factorio/2.0.11/data
   0.011 Write data path: /home/factorio/clusterio/instances/World [86765/100220MB]
   0.011 Binaries path: /home/factorio/clusterio/factorio/2.0.11/bin
   0.034 System info: [CPU: Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz, 4 cores, RAM: 6114 MB]
   0.034 Environment: DISPLAY=<unset> WAYLAND_DISPLAY=<unset> DESKTOP_SESSION=<unset> XDG_SESSION_DESKTOP=<unset> XDG_CURRENT_DESKTOP=<unset> SDL_VIDEODRIVER=<unset> __GL_FSAA_MODE=<unset> __GL_LOG_MAX_ANISO=<unset> __GL_SYNC_TO_VBLANK=<unset> __GL_SORT_FBCONFIGS=<unset> __GL_YIELD=<unset>
   0.035 Running in headless mode
   0.035 Audio is disabled
   0.048 Info ModManager.cpp:434: FeatureFlag expansion-shaders = true
   0.048 Info ModManager.cpp:434: FeatureFlag freezing = true
   0.048 Info ModManager.cpp:434: FeatureFlag quality = true
   0.048 Info ModManager.cpp:434: FeatureFlag rail-bridges = true
   0.048 Info ModManager.cpp:434: FeatureFlag segmented-units = true
   0.048 Info ModManager.cpp:434: FeatureFlag space-travel = true
   0.048 Info ModManager.cpp:434: FeatureFlag spoiling = true
   0.055 Loading mod core 0.0.0 (data.lua)
   0.078 Loading mod base 2.0.11 (data.lua)
   0.318 Loading mod elevated-rails 2.0.11 (data.lua)
   0.359 Loading mod quality 2.0.11 (data.lua)
   0.379 Loading mod space-age 2.0.11 (data.lua)
   0.710 Loading mod base 2.0.11 (data-updates.lua)
   0.737 Loading mod quality 2.0.11 (data-updates.lua)
   0.775 Loading mod space-age 2.0.11 (data-updates.lua)
   0.948 Checksum for core: 1043092351
   0.948 Checksum of base: 708330460
   0.948 Checksum of elevated-rails: 1891730324
   0.948 Checksum of quality: 4264147466
   0.948 Checksum of space-age: 4032004066
   1.665 Prototype list checksum: 124222065
   1.752 Info PlayerData.cpp:66: Local player-data.json available, timestamp 1730066784
   1.752 Info PlayerData.cpp:73: Cloud player-data.json unavailable
   1.754 Info GlobalContext.cpp:1263: Resetting config.
   1.755 Factorio initialised
   1.755 Info Main.cpp:791: Creating new map saves/world.zip
   1.765 Blueprint storage "blueprint-storage-2.dat" was not found, trying to load previous version storage "blueprint-storage.dat"
   3.698 Loading level.dat: 630358 bytes.
   3.698 Info Scenario.cpp:178: Map version 2.0.11-3
   3.720 Blueprint storage "blueprint-storage-2.dat" was not found, trying to load previous version storage "blueprint-storage.dat"
   3.726 Checksum for script __level__/control.lua: 2463946943
Done.
   3.894 Goodbye
[verbose] Patching save
[error] Error preparing instance: Unable to patch save, unknown scenario (bcbdde18ce4ec16ebfd93bd694cd9b12ef969c9a) ```

**Comment by Cooldude2606** [comment]
That error is a result of partial support for factorio 2.0. For now you can only run instances with save patching disabled. We are working on getting full support for 2.0 base game and space age.

Save patching can be disabled within the config of each instance; however this will disable the use of most clusterio plugins. Some such as global chat and discord bridge will still work without save patching.

**Comment by b4xster** [comment]
wow its work, really thanks a lot
